name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echo a test message
        run: echo "Workflow is running!"

      - uses: actions/checkout@v4
        with: 
          lfs: false

      - name: Check Git LFS status
        run: git lfs status

      - name: List repository contents
        run: ls -lR

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Ensure data files are present and up-to-date
        run: |
          mkdir -p data
          for file in cambridge.nodes.json cambridge.ways.json midwest.nodes.json midwest.ways.json mit.nodes.json mit.ways.json; do
            echo "Checking $file"
            if [ ! -f "data/$file" ] || [ ! -s "data/$file" ] || [ "$(wc -c < "data/$file")" -lt 1000 ]; then
              echo "Downloading $file from external source"
              curl -L -o "data/$file" "https://pub-dacce4b1e1694983965461fa4da90666.r2.dev/$file"
            else
              echo "$file is present and not empty ($(wc -c < "data/$file") bytes)"
            fi
          done

      - name: Validate JSON files
        run: |
          for file in data/*.json; do
            echo "Validating $file"
            if ! jq empty "$file" 2>/dev/null; then
              echo "Invalid JSON in $file"
              exit 1
            else
              echo "$file is valid JSON"
            fi
          done

      - name: Check cambridge.ways.json content
        run: |
          echo "First 100 characters of cambridge.ways.json:"
          head -c 100 data/cambridge.ways.json
          echo "\n\nFile type:"
          file data/cambridge.ways.json
          echo "\n\nFile size:"
          wc -c data/cambridge.ways.json

      - name: Increase Maven heap space
        run: echo "MAVEN_OPTS=-Xmx4g" >> $GITHUB_ENV

      - name: List contents of data directory
        run: ls -l data

      - name: Build with Maven
        run: mvn -B clean install -DskipTests

      - name: List contents of target directory
        run: ls -R target

      - name: Run tests
        run: mvn -B -e -X test -Dapp.use.chunking=true
        env:
          MAVEN_OPTS: -Xmx4g

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports
